config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names:
      { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolio', to: 'portfolios#index'
  get 'react-items', to: 'portfolios#react'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  post 'portfolio', to: 'portfolios#create'
  delete 'portfolio/:id', to: 'portfolios#destroy'
  put 'portfolio/:id', to: 'portfolios#update'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'index', to: 'blogs#index'
  get 'blog/:id', to: 'blogs#show'
  # post 'blog', to: 'blogs#create'
  delete 'blog/:id', to: 'blogs#destroy'
  # put 'blog/:id', to: 'blogs#update'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  validates_presence_of :title, :body
  has_many :technologies, dependent: :destroy
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  def self.by_position
    order('position ASC')
  end

  # def self.react
  #   where(subtitle: 'React JS')
  # end
  scope :react, -> { where(subtitle: 'React JS') }

  scope :ruby_on_rails, -> { where(subtitle: 'Ruby on Rails') }

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: %i[edit show update destroy]
  layout 'portfolio'
  access all: %i[show index react], user:
      { except: %i[destroy new create edit update sort] }, site_admin: :all

  def index
    @portfolio_items = Portfolio.by_position
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end
    render nothing: true
  end

  def react
    @react_portfolio_items = Portfolio.react
  end

  def new
    @portfolio_item = Portfolio.new
  end

  def show; end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html {
          redirect_to portfolios_path,
                      notice: 'Portfolio was successfully created.'
        }
      else
        format.html { render :new }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { 
          redirect_to portfolios_path,
                      notice: 'Portfolio was successfully updated.'
        }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    # destroy the record
    @portfolio_item.destroy

    # Redirect
    respond_to do |format|
      format.html do
        redirect_to portfolios_url,
                    notice: 'Portfolio successfully deleted.'
      end
    end
  end

  private # can only be used within this class

  def portfolio_params
    params.require(:portfolio).permit(
      :title,
      :subtitle,
      :thumb_image,
      :main_image,
      :body,
      technologies_attributes: [:name, :id, :_destroy]
    )
  end

  def set_portfolio_item
    # perform the lookup
    @portfolio_item = Portfolio.find(params[:id])
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:, width:)
    "https://via.placeholder.com/#{height}x#{width}"
  end

  def portfolio_img(img, type)
    if img.model.main_image? || img.model.thumb_image?
      img
    elsif type == 'thumb'
      image_generator(height: '350', width: '200')
    elsif type == 'main'
      image_generator(height: '600', width: '400')
    end
  end
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>

  <% if @portfolio_item.errors.any? %>
    <% @portfolio_item.errors.full_messages.each do |error| %>
      <%= alert_generator(error) %>
    <% end %>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: 'form-control' %>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a main image file <%= f.file_field :main_image, style: 'display: none;' %>
        </label>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a thumb image file <%= f.file_field :thumb_image, style: 'display: none;' %>
        </label>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control', rows: 13 %>
      </div>
    </div>
  </div>

  <hr>

  <div class="col-md-6">
    <h2>Technologies Used</h2>

    <div>
      <%= f.fields_for :technologies do |technology_form| %>
        <%= render 'technology_fields', f: technology_form %>
      <% end %>
    </div>

    <div>
      <%= link_to_add_association 'Add Technology', f, :technologies %>
    </div>

    <div class="form-group">
      <%= f.submit 'Save Portfolio Item', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio.html.erb
<div class="col-md-4">
  <div class="card mb-4 shadow-sm" data-id="<%= portfolio.id %>">

    <a href='<%= portfolio_show_path(portfolio) %>' class="my-image">
      <%= image_tag portfolio_img(portfolio.thumb_image, 'thumb'), width: '100%' %>
    </a>

    <div class="card">
      <p class="card-text">
        <span><%=link_to portfolio.title, portfolio_show_path(portfolio) %></span>
        <%= portfolio.subtitle %>
      </p>
    </div>

  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= link_to_remove_association 'Remove Technology', f %>
</div>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
  <h1>Edit this Portfolio Item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">

    <%= source_helper('alert alert-primary') %>

    <%= link_to 'Add portfolio Item', new_portfolio_path, class: 'btn btn-primary new-portfolio' if logged_in?(:site_admin) %>

    <div class="row <%= 'sortable' if logged_in?(:site_admin) %>">
      <%= render @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-container">
  <h1>Create a new Portfolio Item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/react.html.erb
<h1>ReactJS Portfolio Items</h1>

<%= link_to "Create New Portfolio Item", new_portfolio_path if logged_in?(:site_admin) %> <!--new_portfolio_path is a route prefix-->

<% @react_portfolio_items.each do |portfolio| %>
  <h2><%= link_to portfolio.title, portfolio_show_path(portfolio) %></h2>
  <p><%= portfolio.subtitle %></p>
  <p><%= portfolio.body %></p>
  <%= image_tag portfolio.thumb_image unless portfolio.thumb_image.nil? %>

  <%= link_to "Edit", edit_portfolio_path(portfolio) if logged_in?(:site_admin) %>
  <%= link_to "Delete", portfolio_path(portfolio), method: :delete, data: {confirm: 'Are you sure?'} if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag portfolio_img(@portfolio_item.main_image, 'main'), width: '100%' %>
    </div>

    <div class="col-md-5">
      <h2><%= @portfolio_item.title %></h2>

      <hr>

      <em><%= @portfolio_item.subtitle %></em>

      <p><%= @portfolio_item.body %></p>

      <hr>

      <h3>Technologies used:</h3>

      <% @portfolio_item.technologies.each do |t| %>
        <p><%= t.name %></p>
      <% end %>

      <% if logged_in?(:site_admin) %>
        <div class="breadcrumb blogcrumb">
          <%= link_to 'Edit Item', edit_portfolio_path(@portfolio_item), class: 'btn btn-warning' %>
          &nbsp;
          <%= link_to 'Delete Item', @portfolio_item,
                      method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %>
        </div>
      <% end %>
    </div>
  </div>
</div>