config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names:
      { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolio', to: 'portfolios#index'
  get 'react-items', to: 'portfolios#react'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  post 'portfolio', to: 'portfolios#create'
  delete 'portfolio/:id', to: 'portfolios#destroy'
  put 'portfolio/:id', to: 'portfolios#update'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'index', to: 'blogs#index'
  get 'blog/:id', to: 'blogs#show'
  # post 'blog', to: 'blogs#create'
  delete 'blog/:id', to: 'blogs#destroy'
  # put 'blog/:id', to: 'blogs#update'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
    <%= copyright_generator %>
  </div>
</footer>

app/views/shared/_application_navbar.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Joy Too</h3>
    <nav class="nav nav-masthead justify-content-center app-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</header>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p> <%= copyright_generator %> <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">My blog</h1>
    <p class="blog-description"> Blogs here </p>
    <span>
      <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %>
    </span>&nbsp; &nbsp;

    <span>
      <%= link_to 'Topics', topics_path %>
    </span>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<div class="blog-masthead">
  <div class="container">
    <nav class="nav blog-nav">
    <%= nav_helper 'nav-link', 'span' %>
    <%= login_helper 'nav-link' %>
  </nav>
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<aside class="col-md-4 blog-sidebar">
  <div class="p-3 mb-3 bg-light rounded">
    <h4 class="font-italic">About</h4>
    <p class="mb-0">A software developer passionate about technology and all that comes with it.
      I am a lifelong learner always excited about learning new stuff.</p>
  </div>

  <%= source_helper('alert alert-primary') %>

  <div class="p-3">
    <h4>Topics</h4>
    <% @side_bar_topics.each do |topic| %>
      <p><%= link_to topic.title, topics_path(topic) %></p>
    <% end %>
  </div>

  <div class="p-3">
    <h4 class="font-italic">Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://github.com/JoyyToo/"><%= fa_icon "github" %></a></li>
      <li><a href="https://www.linkedin.com/in/joy-too-0558b7154/"><%= fa_icon "linkedin" %></a></li>
      <li><a href="https://www.facebook.com/joyy.too"><%= fa_icon "facebook" %></a></li>
      <li><a href="https://twitter.com/Joytoo97"><%= fa_icon "twitter" %></a></li>
    </ol>
  </div>
</aside>

app/views/shared/_navbar.html.erb
<div class="<%= location %>">
  <div><%= link_to 'Home', root_path %></div>
  <div><%= link_to 'About', about_me_path %></div>
  <div><%= link_to 'Contact', contact_path %></div>
  <div><%= link_to 'Blogs', blogs_path %></div>
  <div><%= link_to 'Portfolio', portfolios_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to 'View all Portfolio Items', portfolios_path %> /
      <a href="#">Back to top</a>
    </p>
    <%= copyright_generator %>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Portfolio</h1>
    <p class="lead text-muted">In this portfolio I've listed some of my favorite projects that I've built through the years.
      These application captures a wide range of the applications that I love to develop.</p>
    <p>
      <%= link_to 'Find out more About Me', about_me_path,  class: 'btn btn-primary my-2' %>
      <%= link_to 'My Blogs', blogs_path,  class: 'btn btn-secondary' %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">In this portfolio I've listed some of my favorite projects that I've built through the years.
            These application captures a wide range of the applications that I love to develop.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Explore</h4>
          <ul class="list-unstyled">
            <%= nav_helper 'text-white', 'li' %>
            <li><%= login_helper 'text-white' %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <strong>Joy Too</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>